---
version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: feycot/weather-app
    env_file: .env
    depends_on:
      - mysql
    ports:
      - 8080:8080
    volumes:
      - .:/app
    command: ["make", "start"]

  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - 33060:3306
    volumes:
      - weather_app:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}

volumes:
  weather_app:
