---
  version: '3'

  services:
    app:
      build:
        context: .
        dockerfile: Dockerfile
      image: feycot/weather-app
      volumes:
        - .:/app
      command: ["make", "lint"]
